name: inv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - attrs=19.3.0=py_0
  - backcall=0.2.0=py_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2020.6.24=0
  - cairo=1.16.0=hcf35c78_1003
  - certifi=2020.6.20=py37_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - cycler=0.10.0=py37_0
  - cython=0.29.21=py37he6710b0_0
  - dbus=1.13.16=hb2f20db_0
  - decorator=4.4.2=py_0
  - expat=2.2.9=he6710b0_2
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.2=h5ab3b9f_0
  - glib=2.63.1=h5a9c865_0
  - gmp=6.1.2=h6c8ec71_1
  - gnutls=3.6.5=h71b1129_1002
  - graphite2=1.3.14=h23475e2_0
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - harfbuzz=2.4.0=h9f30f68_3
  - hdf5=1.10.6=hb1b8bf9_0
  - icu=64.2=he1b5a44_1
  - importlib-metadata=1.7.0=py37_0
  - importlib_metadata=1.7.0=0
  - iniconfig=1.0.1=py_0
  - intel-openmp=2020.1=217
  - ipython=7.17.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - jasper=1.900.1=hd497a04_4
  - jedi=0.17.2=py37_0
  - joblib=0.16.0=py_0
  - jpeg=9d=h516909a_0
  - kiwisolver=1.2.0=py37hfd86e86_0
  - lame=3.100=h7b6447c_0
  - libblas=3.8.0=16_mkl
  - libcblas=3.8.0=16_mkl
  - libclang=9.0.1=default_hde54327_0
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h63c8f33_5
  - liblapack=3.8.0=16_mkl
  - liblapacke=3.8.0=16_mkl
  - libllvm9=9.0.1=h4a3c616_1
  - libopencv=4.4.0=py37_2
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=2.32.1=h14c3975_1000
  - libwebp-base=1.1.0=h7b6447c_3
  - libxcb=1.14=h7b6447c_0
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.9=hea5a465_1
  - lz4-c=1.9.2=he6710b0_1
  - matplotlib=3.2.2=0
  - matplotlib-base=3.2.2=py37h30547a4_0
  - mkl=2020.1=217
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.1.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - more-itertools=8.4.0=py_0
  - ncurses=6.2=he6710b0_1
  - nettle=3.4.1=hbb512f6_0
  - ninja=1.10.0=py37hfd86e86_0
  - nspr=4.22=he6710b0_0
  - nss=3.46.1=hab99668_0
  - numpy=1.19.1=py37hbc911f0_0
  - numpy-base=1.19.1=py37hfa32c7d_0
  - olefile=0.46=py37_0
  - opencv=4.4.0=py37_2
  - openh264=2.1.0=hd408876_0
  - openssl=1.1.1g=h7b6447c_0
  - packaging=20.4=py_0
  - parso=0.7.0=py_0
  - pcre=8.44=he6710b0_0
  - pexpect=4.8.0=py37_1
  - pickleshare=0.7.5=py37_1001
  - pillow=6.2.1=py37h34e0f95_0
  - pip=20.2.1=py37_0
  - pixman=0.38.0=h7b6447c_0
  - pluggy=0.13.1=py37_0
  - prompt-toolkit=3.0.5=py_0
  - ptyprocess=0.6.0=py37_0
  - py=1.9.0=py_0
  - py-opencv=4.4.0=py37h43977f1_2
  - pygments=2.6.1=py_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.12.3=py37h8685d9f_3
  - pytest=6.0.1=py37_0
  - python=3.7.4=h265db76_1
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.6.0=py3.7_cuda10.2.89_cudnn7.6.5_0
  - qt=5.12.5=hd8c4c69_1
  - readline=7.0=h7b6447c_5
  - scikit-learn=0.23.1=py37h423224d_0
  - scipy=1.5.0=py37h0b6359f_0
  - setuptools=49.2.1=py37_0
  - six=1.15.0=py_0
  - sqlite=3.32.3=h62c20be_0
  - swig=3.0.12=h38cdd7d_3
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - toml=0.10.1=py_0
  - torchvision=0.7.0=py37_cu102
  - tornado=6.0.4=py37h7b6447c_1
  - tqdm=4.48.2=py_0
  - traitlets=4.3.3=py37_0
  - wcwidth=0.2.5=py_0
  - wheel=0.34.2=py37_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.11=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h7b6447c_0
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - box2d-py==2.3.8
    - nbmerge==0.0.4
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
prefix: /home/guy.shapira/miniconda3/envs/inv

